# Change these first
owner: fogWraith # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Macintosh Garden
    url: https://macintoshgarden.org
    expectedStatusCodes:
      - 200
      - 403
  - name: DE Archive Mirror
    url: https://old.mac.gdn
    expectedStatusCodes:
      - 200
      - 403
  - name: SE Archive Mirror
    check: "tcp-ping"
    url: 62.116.228.143
    port: 21
  - name: US Archive Mirror
    url: http://mirror.macintosharchive.org
  - name: Macintosh Garden (DEV)
    url: https://macintosh.garden
    expectedStatusCodes:
      - 200
      - 403
  - name: Revontulet
    url: https://revontulet.org
    expectedStatusCodes:
      - 200
      - 403
  - name: System 7 Today
    url: https://system7today.com
    expectedStatusCodes:
      - 200
      - 403

status-website:
  cname: status.macintosh.garden
  logoUrl: https://raw.githubusercontent.com/fogWraith/status/master/assets/Apple_logo_black.svg
  icon: https://raw.githubusercontent.com/fogWraith/status/master/assets/favicon.ico
  name: MG Server Status
  introTitle: "**Macintosh Garden** Server Status"
  introMessage: Knowing is half the battle.
  navbar:
    - title: Status
      href: /
    - title: Macintosh Garden
      href: https://macintoshgarden.org

i18n:
  footer: ''
